[pytest]
filterwarnings =
    ignore::DeprecationWarning
    ignore:distutils Version classes are deprecated:DeprecationWarning
    ignore:distutils Version classes are deprecated:DeprecationWarning:faiss.loader
    ignore:distutils Version classes are deprecated:DeprecationWarning:setuptools._distutils.version
env =
    OPENAI_API_KEY=openaiabcdefghijklmnopqrstuvwxyz
    OPENAI_MODEL=chatgpt
    GEMINI_API_KEY=geminiabcdefghijklmnopqrstuvwxyz
    GEMINI_MODEL=gemini
    GROQ_API_KEY=groqabcdefghijklmnopqrstuvwxyz
    GROQ_MODEL=groq