[pytest]
env =
    OPENAI_API_KEY=openaiabcdefghijklmnopqrstuvwxyz
    OPENAI_MODEL=chatgpt
    GEMINI_API_KEY=geminiabcdefghijklmnopqrstuvwxyz
    GEMINI_MODEL=gemini
    GROK_API_KEY=grokabcdefghijklmnopqrstuvwxyz
    GROK_MODEL=grok